/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_ThroughputTestService          19
#define gattdb_throughput_indications         21
#define gattdb_throughput_notifications       25
#define gattdb_transmission_on                29
#define gattdb_throughput_result              33
#define gattdb_ThroughputInformationService   36
#define gattdb_connection_phy                 38
#define gattdb_connection_interval            42
#define gattdb_responder_latency              46
#define gattdb_supervision_timeout            50
#define gattdb_pdu_size                       54
#define gattdb_mtu_size                       58


#endif // __GATT_DB_H
